conv_backend: cgconv
n_conv_layers: 3
conv_dim: 128
n_hidden_layers: 1
num_elements: 118
activation: relu
radius_cutoff: 8.0
batch_size: 32
max_epochs: 1000
lr: 1.0e-3
weight_decay: 0.01
patience: 100
