#!/usr/bin/env bash
set -euo pipefail

# Submit a SLURM array over a backend's HP-sweep configs (generated by
# 05-generate-sweep-configs.py into targets/<target>/sweeps/<backend>/). Checkpoints land
# in the normal run dir alongside the bake-off ones (lr is folded into the name),
# so 03-evaluate.py --all ranks the sweep and the bake-off together.
#
# Usage:
#   python scripts/05-generate-sweep-configs.py --backend cgconv --cutoff 6
#   ./scripts/06-submit-sweep.sh --target magmom --dataset magmom21-v0p1 --backend cgconv

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}/.."

TARGET="magmom"
DATASET=""
BACKEND=""
WANDB_FLAG=""
SIGNED_FLAG=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --target)  TARGET="$2"; shift 2 ;;
        --dataset) DATASET="$2"; shift 2 ;;
        --backend) BACKEND="$2"; shift 2 ;;
        --wandb)   WANDB_FLAG="--wandb"; shift ;;
        --signed)  SIGNED_FLAG="--signed"; shift ;;
        *) echo "Unknown arg: $1 (try --target/--dataset/--backend)" >&2; exit 1 ;;
    esac
done
[[ -n "${DATASET}" && -n "${BACKEND}" ]] || {
    echo "Usage: $0 --target T --dataset D-vMpN --backend B [--signed] [--wandb]" >&2
    exit 1
}
readonly TARGET DATASET BACKEND WANDB_FLAG SIGNED_FLAG
SUFFIX=""
if [[ -n "${SIGNED_FLAG}" ]]; then SUFFIX="-signed"; fi
readonly SUFFIX

readonly SWEEP_DIR="targets/${TARGET}/sweeps/${BACKEND}"
readonly RUN_DIR="runs/${TARGET}-${DATASET}${SUFFIX}"
readonly LOG_DIR="${RUN_DIR}/logs"
mkdir -p "${LOG_DIR}"

mapfile -t configs < <(find "${SWEEP_DIR}" -name "*.yaml" 2>/dev/null | sort)
[[ ${#configs[@]} -gt 0 ]] || {
    echo "No sweep configs in ${SWEEP_DIR} (run 05-generate-sweep-configs.py first)" >&2
    exit 1
}
readonly N=${#configs[@]}
readonly LIST="${LOG_DIR}/.sweep-${BACKEND}.txt"
printf "%s\n" "${configs[@]}" > "${LIST}"
printf "sweep: %d configs for %s on %s%s\n" "${N}" "${BACKEND}" "${DATASET}" "${SUFFIX}"

batch_file="run-sweep-$$.tmp"
cat > "${batch_file}" << !EOSBATCH
#!/usr/bin/env bash
#SBATCH --job-name=${TARGET}-sweep-${BACKEND}-${DATASET}
#SBATCH --array=1-${N}%4
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gpus=1
#SBATCH --mem=32G
#SBATCH --time=12:00:00
#SBATCH --partition=katla_l40s
#SBATCH --output=${LOG_DIR}/05-sweep-%A_%a.log

source "\${SLURM_SUBMIT_DIR}/scripts/env.sh"

cd "\${SLURM_SUBMIT_DIR}"

CONFIG=\$(sed -n "\${SLURM_ARRAY_TASK_ID}p" "${LIST}")
printf "Config: %s\n" "\${CONFIG}"

python scripts/workers/train.py \\
    --target ${TARGET} \\
    --dataset ${DATASET} \\
    --config "\${CONFIG}" \\
    --device cuda \\
    ${SIGNED_FLAG} \\
    ${WANDB_FLAG}

sleep 2
/usr/bin/sacct -n -j \${SLURM_JOB_ID} \\
    --format=JobID,JobName,MaxRSS,Elapsed,CPUTime --units=MB
!EOSBATCH
JOB_ID=$(sbatch --parsable "${batch_file}")
rm -f "${batch_file}"
printf "Submitted sweep array: %s (%d configs)\n" "${JOB_ID}" "${N}"